"""added next_request_id

Revision ID: 2c6c326a9140
Revises: 9248988f4cfb
Create Date: 2024-08-11 15:53:42.320852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c6c326a9140'
down_revision = '9248988f4cfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_request_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_next_request', 'ad_request', ['next_request_id'], ['id'])
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_request', schema=None) as batch_op:
        batch_op.drop_constraint('fk_next_request', type_='foreignkey')
        batch_op.drop_column('next_request_id')
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###