"""Added name field in Ad_request

Revision ID: 4114dab48555
Revises: 23c4d480a449
Create Date: 2024-07-22 12:37:33.114725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4114dab48555'
down_revision = '23c4d480a449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ad_name', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_request', schema=None) as batch_op:
        batch_op.drop_column('ad_name')

    # ### end Alembic commands ###
