"""adding campiagn to ad_req-2

Revision ID: 5b3ee26b2b7b
Revises: 2a00eda8c099
Create Date: 2024-08-12 01:09:26.267874

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5b3ee26b2b7b'
down_revision = '2a00eda8c099'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_ad_request_campaign', 'campaign', ['campaign_id'], ['id'])

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_request', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ad_request_campaign', type_='foreignkey')
        batch_op.drop_column('campaign_id')

    # ### end Alembic commands ###