"""changes few field names to use in a for loop, in home

Revision ID: f71fb5992855
Revises: 4114dab48555
Create Date: 2024-08-08 17:13:29.250382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f71fb5992855'
down_revision = '4114dab48555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('desc', sa.String(length=255), nullable=True))
        batch_op.drop_column('ad_name')
        batch_op.drop_column('ad_description')

    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desc', sa.String(length=255), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('desc')

    with op.batch_alter_table('ad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ad_description', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('ad_name', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_column('desc')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
